Repository VinayakBector2002/VinayakBector2002, pull requests merged in 2021-10, with the labels that each got.

#44 Add files via upload
  Vinayak Bector_ SPCOM100_ Bongo Presentation.pptx
Labels: hacktoberfest Accepted

#45 Add files via upload
  KuriusBrainCanada.py
Labels: hacktoberfest Accepted

#46 Add files via upload
  1950239.jpg
Labels: hacktoberfest Accepted

#47 Chess Game
  Games for readme/Chess V1.md
Labels: enhancement, hacktoberfest Accepted

#48 Chess Version 2
  Games for readme/Chess V2.md
Labels: enhancement, hacktoberfest Accepted

#49 Added Pokemon Game
  Games for readme/Pokemon Game.md
Labels: enhancement, hacktoberfest Accepted

#50 New Sample Added
  Sample Readmes/Images_TechStack.md
  Sample Readmes/stack-hills.png
Labels: enhancement, hacktoberfest Accepted

#51 Added the Retro
  Sample Readmes/TheRetro.md
Labels: enhancement, hacktoberfest Accepted

#52 Added Game of Ur
  Games for readme/TheGameOfUr.md
Labels: enhancement, good first issue, hacktoberfest Accepted
